package logic;

public enum NoteType {

	WHOLE_NOTE, HALF_NOTE, QUATER_NOTE, EIGHTH_NOTE, SIXTEENTH_NOTE, THIRTY_SECOND_NOTE,
	WHOLE_REST, HALF_REST, QUATER_REST, EIGHTH_REST, SIXTEENTH_REST, THIRTY_SECOND_REST
}
//已添加完全